on: [push]

name: cargo build and jextract
jobs:
  build_and_test:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
  jextract:
    needs: build_and_test
    runs-on: ubuntu-20.04
    name: jextract
    steps:
      - run: sudo apt-get install curl
      - run: curl "https://download.java.net/java/early_access/panama/2/openjdk-16-panama+2-193_linux-x64_bin.tar.gz"  --output "$HOME/openjdk-16-panama+2-193_linux-x64_bin.tar.gz" --etag-save ~/panama.tar.etag 
      - run: cd $HOME && tar xzvf "$HOME/openjdk-16-panama+2-193_linux-x64_bin.tar.gz"
      - run: ls $HOME
      - run: ls $HOME/jdk-16
      - run: cd $GITHUB_WORKSPACE && $HOME/jdk-16/bin/jextract -l rs_handlegraph_ffi -t rs.handlegraph -d java_classes libhandlegraph-ffi-c.h
