on: [push]

jobs:
  build_and_test:
    name: cargo build and jextract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: wei/curl@master
        with:
          args: https://download.java.net/java/early_access/panama/2/openjdk-16-panama+2-193_linux-x64_bin.tar.gz  --output ~/openjdk-16-panama+2-193_linux-x64_bin.tar.gz --etag-save ~/panama.tar.etag 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 16.0.0-ea.2
          jdkFile: ~/openjdk-16-panama+2-193_linux-x64_bin.tar.gz
      - run: jextract -l rs_handlegraph_ffi -t rs.handlegraph -d java_classes libhandlegraph-ffi-c.h
