on: [push]

name: cargo build and jextract
jobs:
  build_and_test:
    name: cargo build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/jdk-16.tar.gz
            ~/jdk-16.tar.gz.etag
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - run: curl "https://download.java.net/java/early_access/panama/2/openjdk-16-panama+2-193_linux-x64_bin.tar.gz"  --output "$HOME/openjdk-16.tar.gz" --etag-save jdk-16.tar.gz.etag --etag-compare jdk-16.tar.gz.etag
      - run: cd $HOME && tar xzvf "$HOME/jdk-16.tar.gz"
      - run: cd $GITHUB_WORKSPACE && $HOME/jdk-16/bin/jextract -l rs_handlegraph_ffi -t rs.handlegraph -d java_classes libhandlegraph-ffi-c.h
